sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rajat333/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajat333/docker-react npm run test